baseURL = "https://chekmenev.com/"
languageCode = "en-us"
title = "Stanislav Chekmenev"
theme = 'stack'

[params]
mainSections = ["posts"]
featuredImageField = "image"
rssFullContent = true
favicon = "/favicon.ico"

[params.colorScheme]
toggle = true
default = "dark"

[params.mermaid]
mermaid.align = "center"

[params.sidebar]
compact = false
emoji = ""
subtitle = "ML specialist & educator"
avatar.enabled = true
avatar.local = true
avatar.src = "img/me.jpeg" 

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "10m"
  [caches.getcsv]
    dir = ":cacheDir/:project"
    maxAge = "10m"
  [caches.images]
    dir = ":cacheDir/:project"
    maxAge = "24h"
  [caches.assets]
    dir = ":cacheDir/:project"
    maxAge = "24h"
  [caches.modules]
    dir = ":cacheDir/:project"
    maxAge = "24h"

[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      Cache-Control = "public, max-age=31536000"

