baseURL = "https://chekmenev.com/"
languageCode = "en-us"
title = "Stanislav Chekmenev"
theme = 'stack'

[params]
mainSections = ["posts"]
featuredImageField = "image"
rssFullContent = true
favicon = "/favicon.ico"

[params.mermaid]
mermaid.align = "center"

[params.sidebar]
compact = false
emoji = ""
subtitle = "ML specialist & educator"
avatar.enabled = true
avatar.local = true
avatar.src = "img/me.jpeg" 


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

